name: undeadreborn
main: hm.moe.pokkedoll.undeadreborn.Main
version: '4.0-SNAPSHOT'
depend: [WorldGuard, WorldEdit]
description: Spawn zombie when player die
author: Emorard
website: https://github.com/Emorard/UndeadReborn

