name: undeadreborn
main: com.pokkedoll.undeadreborn.Main
version: '4.1'
depend: [WorldGuard, WorldEdit]
description: Spawn zombie when player die
author: Emorard
website: https://github.com/Emorard/UndeadReborn

