name: undeadreborn
main: hm.moe.pokkedoll.undeadreborn.Main
version: '2.8-SNAPSHOT'
depend: [WorldGuard]
description: Spawn zombie when player die
author: Emorard
website: https://github.com/Emorard/UndeadReborn

